viatsko/awesome-vscode

- README.md
Fixed the `Lint and IntelliSense` link.
> fix lint link

- README.md
Added [vscode-yo](https://marketplace.visualstudio.com/items?itemName=samverschueren.yo) to the list.
> add vscode-yo

- README.md
Microsoft's version has been deprecated in favor of the community version.
> Link to correct editor config

- README.md
thank you for the awesome-vscode！I once used Atom edit, i like it very much,but some time it's very slow!!! so, now i use vscode instead of Atom。I think the Atom One Dark Theme is very nice!!!
> add  Atom One Dark Syntax Theme

- README.md
> Remove JS-IS-JSX and related parts, no longer required

- README.md
Added Two plugins.
1. Path intellisense which helps in autocompletion of files names in a directory saving lots of time.
2.  Git History which gives detailed history of a line or a file. Extremely useful.  
Regards
Ishan Jain
> Added two plugins

- README.md
Add An Old Hope Theme to awesome-vscode
> Adding an old hope theme

- README.md
It is a great extension which everybody should use if they use any of the C-languages, Rust, JS, TS or Go.
> Added YouCompleteMe to C/C++ linters

- README.md
You [invited](https://medium.com/@viatsko/hey-sebastian-89890560db34#.nlly433ti) me to add my favorites, so I did!
> Added my extension suggestions

- README.md
* Add 3 extensions
* Code Runner 
* Auto Close Tag
* Azure IoT Toolkit 
* Add gif for Auto Rename Tag
> Add 3 extensions

- README.md
https://github.com/flagello/Essence
https://github.com/orta/Essence
> Adds UI Forks of VS Code

- README.md
Added paste and indent extension which automatically corrects the indentation of the pasted code according to the user's current indentation.
> add paste and indent extension

- README.md
- Modify path to GitLens preview
- Added GitLens to table of content
> Fixes for GitLens package in README.md

- README.md
Helps in formatting your JavaScript by parsing and pretty printing a consistent syntax 
A simple `CMD + Shift + P` does the magic
> Add "Prettier" - JavaScript Formatter

- README.md
Much better than official C/C++ extension.
> Add Clang autocomplete

- README.md
Added the 'Output Colorizer' extension, which adds regex-based colorization to the Visual Studio Code "Output" panel.
> Added 'Output Colorizer'

- README.md
Partial Diff. Allows you to execute not only file-to-file but more granular text comparisons.
> Added "Partial Diff"

- README.md
> added 'Deploy' extension

- README.md
Added **vscode-spotify** to _Uncategorized_  list
> Added vscode-spotify

- README.md
I have tried and feel better than other. support directly.
> change Arduino Extension by Microsoft

- README.md
> add 1C-Syntax package

- README.md
Just add my git extension.
Github: [https://github.com/lamartire/vscode-git-indicators](https://github.com/lamartire/vscode-git-indicators)
Marketplace: [https://marketplace.visualstudio.com/items?itemName=lamartire.git-indicators](https://marketplace.visualstudio.com/items?itemName=lamartire.git-indicators)
> Add git-indicators

- README.md
@viatsko I know the format of this suggestion doesn't follow the outline in contributing.md, but it's an auxiliary tool for creating themes rather than a theme found in the marketplace. I'm happy to change things around if you wish. Thanks for considering!
> Add link to themer to tools section.

- README.md
And fixed a typo in TOC heading
> Added Kotlin extension

- README.md
I'm using this for quite some time and it has saved my time when developing static HTML templates.
It creates a live server with live reload built into it. 
Now also dynamic pages like PHP.
> add Live Server extension

- README.md
Added [KL](https://marketplace.visualstudio.com/items?itemName=melmass.kl) (fabric engine) and [VEX](https://marketplace.visualstudio.com/items?itemName=melmass.vex)(houdini) syntax
> Added KL (fabric engine) and VEX(houdini) syntax

- README.md
`Better Align` just like that name :D more better.
> change Align Extension

- README.md
more info on extension [here](https://github.com/gko/wrap)
> add «Wrap Selection» extension

- README.md
Edit with Shell Command allows you to use your shell commands to edit the text you selected
> Added "Edit with Shell Command"

- README.md
A useful extension that makes life easier, if you need to browse your database. Way more pleasant than the Mongo DB shell.
>  Azure Cosmos DB added to Productivity extensions

- README.md
Added:
* C# FixFormat
* C# Extensions
Resolving issue #77 
* C# FixFormat
- Allows users to clean up their code and format their files for better code readability. 
* C# Extensions
- This extension speeds up C# development with loads of features like adding classes, interfaces and dealing with constructors.
> Added Extensions for C#

- README.md
Add [Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) VS Code theme to the list
[Shades of Purple](https://marketplace.visualstudio.com/items?itemName=ahmadawais.shades-of-purple) VS Code theme.
I love purple, purple can be genius. So, I created a theme after spending an entire week on each and every single color attribute. With hand-picked colors, I think this theme looks pretty awesome.
---
> 💜 Add Shades of Purple Theme

- README.md
CSS Peek
1. Let's you easily edit CSS/SCSS/LESS without having to context switch away from your HTML file
2. No more Cmd+F when trying to find where the style for an element comes form
3. I built it 😛
> Add CSS Peek

- README.md
Hey! I’m the author of this extension and I’d love if it could be added to the README :) I’m using it daily and there were issues about it in multiple related projects, which proves it’s something people needed.
https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle
> Add Formatting Toggle extension

- README.md
> add captain sweetheart

- README.md
Text Marker (Highlighter)
This extension allows you to highlight multiple text patterns at the same time. Highlighting a single text pattern is possible by using the editor's search functionality, but it cannot highlight multiple patterns at the same time, and this is where this extension comes handy.
It helps you in the situations like following:
* To understand what's going on in the system by highlighting multiple keywords (like certain user id, ip address, ...) in log files (like access log, application log, ...)
* To be sure if system is correctly configured by highlighting multiple keywords through multiple source code or configuration files
* To understand which bit of code has reference to which variables/methods by highlighting all of them at the same while you read rather …
> Added "Text Marker (Highlighter)"

- README.md
Debugger for Java
It's an awsome tool to debug Java code in VS Code. It's also pretty stable and works very well.
> Add Java Debugger to the Java Section

- README.md
Surround
It makes code refactoring much easier.
> add surround

- README.md
GitHub Pull Request Monitor
Helps to monitor the state of your GitHub PRs without switching windows.
> Add GitHub Pull Request Monitor

- .travis.yml
- README.md
Linkify themes images. Follow up to https://github.com/viatsko/awesome-vscode/pull/126.
> Added theme image links

- README.md
Firebase Bolt
...
This add syntax support of firebase bolt language to vscode.
...
None of the other syntax extensions contains the screenshot so didn't add.
There is not details ToC no nothing changed.
> Added my bolt language vscode extension.

- README.md
Kanban board for use in Visual Studio Code, with time tracking and Markdown support.
The is a good solution for all, who need (or want) a simple and powerful offline kanban board within their workspace(s) for their project management.
> Add vscode-kanban

- README.md
I've made some recent changes to the site and now supports more themes. This PR updates the remaining marketplace links.
> Updated vscode themes links

- README.md
https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
...
Markdown Preview Enhanced is an extension that provides you with many useful functionalities such as automatic scroll sync, math typesetting, mermaid, PlantUML, pandoc, PDF export, code chunk, presentation writer, etc. A lot of its ideas are inspired by Markdown Preview Plus and RStudio Markdown.
...
> add md preview

- README.md
[Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)
- highlights keywords e.g. TODO
- allows user to add/remove keywords
- customize per keyword highlighting, including background color, text color, and type
> added todo tree

- README.md
https://marketplace.visualstudio.com/items?itemName=steoates.autoimport
...
Automatically finds, parses and provides code actions and code completion for all available imports. Works with Typescript and TSX.
...
[ x ] Screenshot/GIF included (to demonstrate the plugin functionality)
> add auto import

- README.md
https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare
...
Visual Studio Live Share enables you to collaboratively edit and debug with others in real time, regardless what programming languages you're using or app types you're building. It allows you to instantly (and securely) share your current project, and then as needed, share debugging sessions, terminal instances, localhost web apps, voice calls, and more! Developers that join your sessions recieve all of their editor context from your environment (e.g. language services, debugging), which ensures they can start productively collaborating immediately, without needing to clone any repos or install any SDKs.
...
> add live share

- README.md
.NET Core Test Explorer
It lets you view/run your tests much like you would in any other full IDE!
> Add .NET Core Test Explorer extension

- README.md
[City Lights Icon Package](http://citylights.xyz)
It's a combination between colored and grayscale icons (see GIF for details)
> Add City Lights Icon Package + preview

- README.md
Toggle Quotes
Super handy when writing JavaScript
> Add toggle Quotes extension

- README.md
Laravel Model Snippets
This is a shortcut of snippets within Data Models in the Laravel PHP Framework. These snippets save developers from having to hand write several lines of code.
> Add Laravel Model Snippets

- README.md
Material Icon Theme
Upon activation it instantly allows folder and file icons to have a material design
[ x] Screenshot/GIF included (to demonstrate the plugin functionality)
[ x] ToC updated
> Included Material Icon Theme under Explorer Icons

- README.md
reason-vscode
It's the official extension for ReasonML
> Add ReasonML

- README.md
It provides parameter hints / annotations into VS Code for TS / JS files so you can look at your code base and get clarity to function calls with primitive values as arguments
> Adding JS Parameter Annotations extension

- README.md
autocomplate-shell
This extension adds rich language support for the shell script to VS Code
> add shell support

- README.md
- Rename the section on keymaps to **Migrating from other Editors**
- Move `vm-mode` to **Migrating from Vim**
- Fix #168
> Change Keymaps to "Migrating from other Editors"

- README.md
> remove Copy Relative Path extension

- README.md
vscode-terraform
It doesn't only highlight and validate the syntax, but also can tell us how many resources reference to the certain resource. 
> Add Terraform to Lint list

- README.md
ES7 React/Redux/GraphQL/React-Native snippets
It increases efficiency when working with nodejs/reactjs by enabling short codes to create repetitive functions/imports/exports etc
[ x] Screenshot/GIF included (to demonstrate the plugin functionality)
Doesn't included screenshot or GIF but contains a table to show examples of snippets
[ x] ToC updated
> Included ES7 React/Redux/GraphQL/React-Native snippets under Productivity

- README.md
Remote VSCode
editing files at remote server with CLI only(especially Azure VM or Google Cloud Platform) is always a pain, unless you are familiar with Vi/Emacs or similar editor.
By using the extension, with some settings, enable the user to edit the file at your familiar text editor.
[X ] Screenshot/GIF included (to demonstrate the plugin functionality)
No GUI, it's using terminal to connect the remote server.
[ X] ToC updated
> Added Remote VSCode

- README.md
Calva
...
Full-blown IDE for Clojure development in VSCode
...
> Calva - IDE for Clojure

- README.md
Markdown All in One
A great tool for writing markdown with lots of useful features, including but not limited to live preview, quick generation of table of contents, keyboard shortcuts and math rendering.
> Add Markdown all in one

- README.md
> removed "Preview" from Microsoft C# extension

- README.md
Bash Debug
A easy-to-use debugger for debugging Bash script. It also provides wonderful GUI for debug control that is seemlessly integrated into vscode.
> Add Bash Debug

- README.md
WakaTime
It increases my productivity.
> Add WakaTime to Productivity section

- README.md
> haskell and c++ updates

- README.md
TypeScript Hero
It's essentials when developing with angular
[x ] Screenshot/GIF included (to demonstrate the plugin functionality)
[x ] ToC updated
> Add TypeScript Hero

- README.md
Follow up to https://github.com/viatsko/awesome-vscode/pull/201
> Updated rainglow links

- README.md
Reverts viatsko/awesome-vscode#220
> Revert "Add course to the list "

- README.md
I am adding my [VSCode.pro](https://VSCode.pro/) power user course to the list. I have spent a lot of time and energy in building this course. With my 🦄 Shades of Purple theme ranking in top ten marketplace theme, I knew people would love to learn how I have set up my editor and more.
...
This course is easily my best work to date. I have built the workflows, custom theme, custom platform, custom landing pages, to emails written with React/Markdown. Even got a chance to contribute to the core software code of VSCode and got props. Proud of my work AH. About a 1,400 developers have signed up for the course already.
@viatsko I am happy to provide you with a free review copy of the master class. Kindly, [DM me at Twitter](https://twitter.com/MrAhmadAwais/) or [send me an …
> 📦 NEW: VSCode.pro Course

- README.md
Vscode Google Translate
Because you can do i18n with ease without moving from vscode.
> added vscode google translate extension

- README.md
shell-format
can formart shell script , Dockerfile ,dotenv ...
> add  vs-shell-format extension

- README.md
Interface generator (dotup.dotup-vscode-interface-generator)
Quickly generate interface definitions from typescript classes. Supports all class keywords except comments.
> Add Typescript Interface Generator

- README.md
Edits:
keybindings (5) ----> key bindings
Levarage -----------> Leverage
Yummygumm -----> Yummygum
colorblindness -----> color blindness
lanched ------------> launched
> Edited grammatical and typo errors

- README.md
Code Time
You can generate time reports by project right in VS Code
> Add Code Time

- README.md
GitLab Workflow
Brings a bunch of the great features of GitLab into the VSCode interface.  Almost 200k downloads!  That's pretty awesome too.
> Add GitLab workflow extension 

- README.md
PrintCode is the most feature rich code printer in VS Code
PrintCode
...
I have tried many different Code Printing tools.  This one seems to work the best.  It formats the code correctly every time and will also print code blocks.  Also adds an icon to the top right of the screen making it easier to print.
...
- [ X] Screenshot/GIF included (to demonstrate the plugin functionality)
- [ X] ToC updated
> Add PrintCode to README

- README.md
Camel humps
Makes writing code better
> Added camel humps (Key map settings)

- README.md
Shader languages support for VS Code
Very basic need for shader coding
No screenshot neither ToC (followed format for syntax)
> Added Shader languages support for VS Code

- README.md
Fix Night Owl Image not showing on mobile chrome.
> FIX Night Owl Image on Mobile Chrome

- README.md
> Added Julia to Language packages

- README.md
It is truly a game changer
Visual Studio IntelliCode
It provides truly useful autocomplete that understands context in your application and suggest the most useful autocomplete suggestions possible.
https://docs.microsoft.com/en-us/visualstudio/intellicode/media/python-intellicode.gif
> Added Visual Studio IntelliCode.

- README.md
Ascii Tree Generator
Makes creating ascii trees a breeze.
> Add ascii tree generator

- README.md
ARM Template Viewer
Pretty nifty way to visualize the impact of deploying ARM templates.
> Added ARM Template Viewer

- README.md
[i18n Ally](https://github.com/antfu/i18n-ally)
It works for may major frameworks that make i18n & i10n development much easier and reliable.
> Add i18n Ally

- CONTRIBUTING.md
- README.md
Remote Development
This extension saves a lot of time and makes working on projects that are on remote servers or containers very seamless.
> Added Remote Development

- README.md
[Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens)
It's the best extension of the ones that highlight diagnostics.
> Add Error Lens

- README.md
extension maintainer has created a new version of this plugin.
old extension unpublished from Visual Studio Marketplace.
this change updates the url to the extension and the preview gif
Calva: Clojure & ClojureScript Interactive Programming
It's just as awesome as the old Calva plugin :-)
> Update Clojure plugin

- README.md
Jira and Bitbucket
https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode
It's a full-featured extension that allows developers using Jira and Bitbucket to create pull requests, do code reviews, create pipeline builds, create issues, get notified on builds, and many more, directly from VSCode.
> Add Jira and Bitbucket

- README.md
Markdown Emoji
Pretty handy to see emoji in the built-in markdown previewer
> Added Markdown Emoji

- README.md
Code Spell Checker
Code Spell Checker is really useful for developers to check typo.
> Add code spell checker for Awesome vscode

- README.md
Tinacious Contrast Color Theme (https://marketplace.visualstudio.com/items?itemName=sugarpirate.theme-tinacious-contrast)
...
This is a nice them but not very known by the community. As well, This is confortable to code at night with it.
...
> Add Tinacious Theme

- README.md
[Shellman](https://marketplace.visualstudio.com/items?itemName=Remisa.shellman)
Allows to learn Bash Scripting with examples
> Add shellman to Bash section

- README.md
[AutoHotkey](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey)
[AutoHotkey++](https://marketplace.visualstudio.com/items?itemName=vinnyjames.vscode-autohotkey-vj)
[AutoHotkey Manager](https://marketplace.visualstudio.com/items?itemName=Denis-net.vscode-ahk-manager)
A top set of extensions if you are going to write some `ahk` scripts
> Add AutoHotkey section

- README.md
Rainbow CSV
Useful for working with CSV files. Adds syntax highlighting, transformation, linting and RBQL querying features.
> Add Rainbow CSV

- README.md
[vscode-clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd)
It gives a better IntelliSense and autocompletion from the others and also has a better features like refactoring.
> Add clangd

- README.md
- ❌Deleted an outdated extension [AutoHotkey](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey). Out of all language features it contributed only Snippets and Syntax Highlighting. The last commit was 2 years ago.
- ❌Deleted an extension [AutoHotkey++](https://marketplace.visualstudio.com/items?itemName=vinnyjames.vscode-autohotkey-vj) which is a fork of [AutoHotkey Plus](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-autohotkey-plus), but has less functionality and doesn't look maintained
- ✔Added an extension [AutoHotkey Plus](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-autohotkey-plus)
Most of the extensions are forks of outdated [AutoHotkey](https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-auto …
> Change AutoHotkey section

- README.md
[Project Dashboard](https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard)
It makes managing and switching between multiple projects quick and easy. No more fiddling around with folders or the list of recent folders.
(closes #308 )
- [x ] Screenshot/GIF included (to demonstrate the plugin functionality)
- [x ] ToC updated
> Included vscode-dashboard

- README.md
[Typescript Destructure](https://marketplace.visualstudio.com/items?itemName=tusaeff.vscode-typescript-destructure-plugin)
There is a common code style in the React development: you get the object as an function' argument and destructure it. Like that:
```typescript
function Component(props) {
const { a, b, c } = props; 
}
```
It's exhausting to copy all the properties of an object every time. This extension allows you to paste this `const { a, b, c } = props` in one click (instead of manually writing all the necessary properties)!
p.s. it's my second pr to this repository, I hope you're not tired of me yet.
> Added Typescript Destructure

- README.md
[POV-Ray](https://marketplace.visualstudio.com/items?itemName=jmaxwilson.vscode-povray)
Have syntax highlighting for the POV-Ray scene description language, code snippets, ability to render the scene directly from Visual Studio Code.
> Added POV-Ray to Syntax and Lint and IntelliSense

- README.md
Text Power Tools
Text Power Tools is an all-in-one extension for text manipulation: it contains commands for filtering (grep), removing lines, inserting number sequences and GUIDs, formatting content as table, changing case, converting numbers and more.
> Add Text Power Tools to the list of Productivity extensions

- README.md
Smarty Template Support
Provides smarty template support with formatting, folding, snippets, syntax highlighting and more
> Added Smarty Template Support

- README.md
[ngrok for VSCode](https://marketplace.visualstudio.com/items?itemName=philnash.ngrok-for-vscode) 
[ngrok](https://ngrok.com) is a tool that opens a tunnel between a public URL and your locally running application server. Rather than having to open a terminal window to run ngrok you can do so from within VSCode.
It also reads your ngrok config file and allows you to open named tunnels or just provide a port number.
Hope you think it's awesome too!
> Adds ngrok for VSCode to the list.

- README.md
CodeRoad
Uses VSCode in a novel way to play coding tutorials like a game.
> add CodeRoad

- README.md
Parameter hints
It will make your functions more readable.
> Added parameter hints

- README.md
Password Generator
- We're always going through a lot of different softwares/sites to create/generate passwords for new registers, this extension will avoid it.
- Second extension with this purpose on the World
- You can fast copy the generated password
...
> docs: adding password generator extension

- README.md
[Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete)
- It provides path completion and it is very useful for productivity 
- It also supports relative paths (starting with ./)
- It supports absolute path to the workspace (starting with /)
- It supports absolute path to the file system (starts with: C:)
- It supports paths relative to the user folder (starts with ~)
- It supports automatic suggestion after selecting a folder
> Added extension 'Path Autocomplete'

- README.md
HLSL Tools - https://marketplace.visualstudio.com/items?itemName=TimGJones.hlsltools
I guess I can't just say, because I made it?
HLSL Tools provides a language server for editing HLSL files in VS Code, including statement completion, signature help, quick info, go-to-definition, reference highlighting, and more.
> Add HLSL Tools

- README.md
[TS/JS postfix completion](https://marketplace.visualstudio.com/items?itemName=ipatalas.vscode-postfix-ts)
This is literally the best extension for JS/TS in VSCode. I can't really say how much it made me more productive with writing JS/TS code.
Works almost in all cases and as I think even better than postifixes in WebStorm.
Builtin snippets are nothing in comparison with actual extension possibilities.
Top use cases:
> Note: `|` means tabstop
>
```ts
fs.existsSync().if -> if (fs.existsSync())
```
```ts
fs.promises.readFile().await -> await fs.promises.readFile()
```
```ts
await fs.promises.readFile().const -> const name = await fs.promises.readFile()
```
> Above also can be used for destructuring
```ts
await fs.promises.readFile().log -> console.log(await fs.promises.readFile())
``` …
> Add TS/JS postfix completion

- README.md
PHP Tools
All-in-one extension for PHP language.
> Add PHP Tools extension

- README.md
...
Incredibly useful for quick MATLAB editing without firing up the whole application.
...
> Add Mathworks MATLAB extenison.
