viatsko/awesome-vscode

README.md

[Ionide](ionide.io) is a bunch of VS Code plugins. Adds an awesome support for an awesome F# language and tools: FAKE and PAKET (installed separately)

add Syntax-F# - link to ionide suite

---

README.md

Something like this? Or would you put `vscode-set-text` directly under `Resources for extension developers`?

add vscode-set-text

---

README.md

The original C++ link points to "#c++" which is incorrect (It should be "#c").
It seems that plus signs are removed during parsing.

Fix C++ link in Table of Contents

---

README.md

The original package has been deleted.
We can use [this](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) to replace it.

Update Project Manager

---

README.md

While adding the extension, I noticed that the alphabetical ordering was off and Vim Mode was missing from the table of contents, so I fixed this as well.
It also seems that the Vim Mode image is currently broken (couldn't find an alternative one in the repo either).

Add SVG viewer and fix ordering

---

README.md

Removing deprecated theme extension (I'm the author), vscode now has a UI theming feature, see https://github.com/Microsoft/vscode/issues/1884#issuecomment-290940262

Remove deprecated extension

---

README.md

Adds the following extensions to README.md
- `npm intellisense` to `Productivity` section
- `Intellisense for CSS class names` to `CSS` section
Also adds the following sections
- File Icons - For File Explorer Icons
- Keymaps - For Keymap extensions

Add more extensions and new sections

---

README.md

Hi @viatsko! 
I've added the Ariake Dark color theme — it's minimalistic dark ui scheme and I think, it's really awesome:)
Is there any things I should do to get this PR merged?

add Ariake Dark color theme

---

README.md

We transferred Dart Code from the DanTup publisher to one named Dart-Code. The old URL now displays a message linking here.

Update link to Dart Code

---

README.md

I noticed that it was missing, despite this section being in the page content. I hope this helps.

adds migrating-from-intellij-idea to ToC

---

README.md

Fix a missing "-" in "#git-indicators"

Fix Git Indicators anchor link

---

README.md

Multi protocol support for things, like Azure blobs, S3 buckets, Dropbox, (S)FTP or WebDAV files, by using new [FileSystem API](https://code.visualstudio.com/docs/extensionAPI/vscode-api#FileSystemProvider), especially for accessing resources like local files and folders in the editor as [workspace folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces).
You can add one or more remote folders by a simple and powerful URI configuration as [workspace folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces).
The extension supports:
* AWS S3 buckets
* Azure blobs
* Dropbox
* FTP(s)
* SFTP
* Slack
* WebDAV
Example for accessing a S3 bucket, by creating (or editing) and opening a `*.code-workspace` file:
```json
{
"folders": [{
"uri": …
```

added Remote Workspace

---

README.md

Hive-SQL
...
This extension provides syntax highlighting and formatting for Hive SQL.
...
Not provided, to maintain consistency with other "Syntax" entries.
n/a

adding extension to support Hive SQL

---

README.md

Just changing a few instances of "Github" to be "GitHub".

Standardize spelling of GitHub

---

README.md

flatbuffers idl
https://google.github.io/flatbuffers/flatbuffers_grammar.html
flatbuffers syntax highlighter.
makes it easy to write the flatbuffers based schema in visual studio code.

Added link for flatbuffers syntax highlighter

---

README.md

Closes #169.
I created a list of active people on Twitter that promote VS Code & the community. There are likely more people to add to it, but this is a good start.
Rather than merging it in directly I will have at least one other collaborator review it and merge it in.

Adding list of people to follow related to @code

---

README.md

Befunge
Adds language support and alignment guides for the Befunge-93 and Funge-98 esolangs - alignment guides are quite helpful in a language which takes advantage of directionality
- not included, as it doesn't look like any other language syntaxes included one. However, here is a screenshot:

Add Befunge to syntax list

---

README.md

[highlight-matching-tag](https://marketplace.visualstudio.com/items?itemName=vincaslt.highlight-matching-tag)
...
This was one of the missing features when migrating from WebStorm.
...

Adding highlight-matching-tag to the list

---

README.md

Rainglow
rainglow.io is a collection of 320+ beatuify cross-editor syntax and UI themes. The themes are available for some terminals as well, so you can very easily make your terminal and editor look alike.
Since this extension does not have a UI, and I didn't want to screenshot one specific theme (because it's a collection of many), so I added the Rainglow logo, I'm not sure if it suffices.

Add Rainglow

---

README.md

MS Build Project Tools
MSBuild Project Intellisense Support via the Language Server Protocol, Intellisense for Nuget Packages
The second is the most common case, and in many cases beats out the Visual Studio IDE support for Nuget packages, as the lookup is faster, and more direct since you're changing the project file directly. I am sure the first case will be extremely helpful to many who forget the obscure and arcane MSBuild project file syntax due to the infrequency of having to modify them.
- [!] ToC updated
C# TOC already exists

Add MSBuild Project Tool extension to C# language section

---

README.md

* Instant Markdown
* Import Cost
...
* displays in the browser
* fast
* highlights import size of packages
* easily see largest imports right in the editor
* find sub module to install rather than entire package as shown in gif
...

added instant markdown and import cost

---

README.md

Format HTML in PHP
If you quickly google "How do I format the HTML in PHP files?" you will find multiple VSCode github issues and Stackoverflow posts about this long standing issue. This extension fixes it while still allowing you to register a normal PHP formatting extension because it does the work onBeforeSave and also gives you a keybinding.
- [ X ] Screenshot/GIF included (to demonstrate the plugin functionality)

Add Format HTML in PHP extension

---

README.md

Switched the creative commons icon, online TextMate themes editor, and YouCompleteMe links to https.
there isn't one
yes

Switch links to using https

---

README.md

ColorTabs
One of the few extensions that target working in monorepos or big projects. It can:
1. Color your active tab
2. Color your titlebar
3. Add a custom label to your title bar
All based on a list of rules you provide, so for example, if you're working on a react+react-native project you can say
`*/mobile/*` -> `red`
`*/green/*` -> `green`

add ColorTabs extension

---

README.md

Indent Rainbow
Make indentation really visible in languages where number of tabs/spaces matters (python, yaml, etc). When you get wrong number of spaces (for example, 3 instead of 4) extension will highlight the line with red marker.

Add intent rainbow

---

README.md

Gradle Tasks
https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-gradle
It's a missing feature of VS Code. No other Gradle related extension provides the ability to list and run tasks.

Add Gradle Tasks

---

README.md

文言 Wenyan Lang
https://marketplace.visualstudio.com/items?itemName=antfu.wenyan-lang
It's the only vscode out there that supports [Wenyan Lang](https://github.com/LingDong-/wenyan-lang), a programming language for the ancient Chinese which grows rapidly in recent weeks.
This extension supports syntax highlight, snippets, direct executing, compiling, rendering and more.
I am not sure whether a syntax plugin should provide a screenshot or not. However here it is.

Add Wenyan Lang for VSCode

---

README.md

[GistPad](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.gistfs)
GistPad makes it extremely easy for developers to leverage GitHub Gists as their personal library of code snippets and developer notes. It adds a bunch of helpful features on top of gists, such as allowing you to organize your files into [directories](https://github.com/vsls-contrib/gistpad#files-and-directories), [inline commenting](https://github.com/vsls-contrib/gistpad#gist-commenting), [grouping](https://github.com/vsls-contrib/gistpad#sorting-and-grouping), and the ability to [follow your friends](https://github.com/vsls-contrib/gistpad#following-users).
Additionally, it lets you create [CodePen-like playgrounds](https://twitter.com/LostInTangent/status/1207718123241033728) / …

Adding GistPad

---

README.md

VsCode Groovy Lint
Because CodeNarc groovy linter is a nice tool but wasn't available for VsCode, and there was also no way to format or automatically fix the errors ... and now there is , we can finally build our shared libraries in VsCode and have a linter, formatter and correcter with a single extension :)

Add Groovy category in linters index, and add VsCodeGroovy lint  gif

---

README.md

[iTerm2 Theme Sync](https://marketplace.visualstudio.com/items?itemName=tusaeff.vscode-iterm2-theme-sync)
How this extension helps me every day:
1. I no longer think about what theme I have chosen in the terminal - now I have one VSCode theme to rule them all.
2. I no longer find myself in a situation where I have a dark theme in the editor and a light theme in the terminal (or vice versa) - now my eyes do not hurt when I switch between them.
I think a lot of people experience similar problems and this extension can help solve them :)

Added iTerm2 theme sync 

---

README.md

Timing
It eases timestamp conversion. It enhances productivity when you have to deal a lot with database or log file timestamps.
Just hover over an epoch timestamp and it shows you the corresponding UTC one.

Add timing extension

---

README.md

That's a very tiny change to fix a typo to one of the Contributor's Twitter account.

Fix: mattbierner Twitter link typo

---

README.md

I have updated TOC with Markdown All in One, thats why some additional sections were added (but I think this even better).
- **tslint** deprecated in favor of ESLint
- **Settings Sync** It is now built-in VSCode feature
Also removed some outdated libraries.
Note, that TypeScript hero is also outdated (it has some bugs and performance problems), but I don't any alternative to it right now.
- [XXX] ToC updated

remove outdated / deprecated extensions

---

README.md

- SmoothType: `editor.cursorSmoothCaretAnimation`
- Bracket Pair Colorizer: `editor.bracketPairColorization.enabled`
- TypeScript Hero: replaced by better builtin TypeScript language features extension
fixes #347

remove extensions that are now replaced by builtin settings 

---

README.md

Duplicated image from Text Marker (Highlighter) section
fixes #341

Remove vscode-text-marker duplicated image

---

README.md

Initially I wanted to open 2prs with two extensions, but instead I've grouped them into this pr.
So I introduced new section for github extensions only, because there are growing numbers of them. I think it should make sense, hovewer, maybe I should move it below the productivity section or make it subsection of *Productivity*?
- GitHub Actions (unofficial)
- GitHub Repositories (official)
- GitHub Pull Requests and Issues
- GitHub Actions - provides only the way to view actions within IDE. Also it adds completions for workflow files and error highliting.
- GitHub Repositories - closed-source extension for opening GitHub repositories in virtual workspace (without cloning)

Introduce `GitHub` section with new extensions

---

README.md

Hey! Some time ago I've an idea of creating framework for vscode development that would care of adding links, ids, bundling and so on. I've abandoned it, however the library I'm adding isn't part of this ecosystem and its pretty stable and covered with integration tests.
This library improves DX only, it does nothing at runtime
Just why not, AFAIK there is no other way to achieve something like that.

Add `typed-vscode` to libraries

---

README.md

Fix project's description and status badge that consist of unsupported syntax on static site. 
...

Fix: Markdown syntax support to static site

---

README.md

Moved Browser Preview to Productivity; Added deprecated tag

---

README.md

Rust-Analyzer
The old Rust extension was depreciated because Rust-Analyzer was better.
A screenshot is not included as it wasn't included with the old extension, and there isn't much to show.

Fixes issue #387
